# Generated by Django 4.2 on 2026-04-23 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(blank=True, help_text="User's age", null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, help_text='Where the user lives', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='occupation',
            field=models.CharField(blank=True, help_text="User's occupation", max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='university',
            field=models.CharField(blank=True, help_text='University name if student', max_length=100),
        ),
    ]
