# Generated by Django 4.2 on 2026-04-21 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the group (e.g., 'Summer Vacation 2025')", max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of what the group is for')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='User who created the group', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"group"',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('member', 'Member')], default='member', max_length=50)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='groups.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'membership',
            },
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['group', 'user'], name='membership_group_i_cb1947_idx'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['user'], name='membership_user_id_4a088d_idx'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['group'], name='membership_group_i_a7589a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('group', 'user')},
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['created_by'], name='group_created_3a03c7_idx'),
        ),
    ]
