# Generated by Django 4.2 on 2026-04-21 11:25

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text="Total expense amount in group's currency", max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('description', models.CharField(blank=True, help_text='What was the expense for?', max_length=500)),
                ('category', models.CharField(choices=[('accommodation', 'Accommodation'), ('food', 'Food & Dining'), ('transport', 'Transportation'), ('entertainment', 'Entertainment'), ('utilities', 'Utilities'), ('shopping', 'Shopping'), ('other', 'Other')], default='other', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='groups.group')),
                ('paid_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses_paid', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'expense',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Split',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount this user owes for this expense', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='expenses.expense')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_splits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'split',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Settlement amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('description', models.CharField(blank=True, help_text="Payment description (e.g., 'Settled for split dinner')", max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_made', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='groups.group')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='split',
            index=models.Index(fields=['user'], name='split_user_id_7371d2_idx'),
        ),
        migrations.AddIndex(
            model_name='split',
            index=models.Index(fields=['expense'], name='split_expense_c55b62_idx'),
        ),
        migrations.AddIndex(
            model_name='split',
            index=models.Index(fields=['user', 'expense'], name='split_user_id_deb83a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='split',
            unique_together={('expense', 'user')},
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['from_user'], name='payment_from_us_040497_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['to_user'], name='payment_to_user_8cf935_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['group'], name='payment_group_i_68e5ca_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['created_at'], name='payment_created_6be7be_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['from_user', 'to_user', 'group'], name='payment_from_us_c2285c_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['group'], name='expense_group_i_f5636a_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['paid_by'], name='expense_paid_by_42b0f3_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['created_at'], name='expense_created_0a6070_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['group', 'created_at'], name='expense_group_i_66deea_idx'),
        ),
    ]
