# Generated by Django 4.2 on 2026-04-22 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Confirmation'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', help_text='Settlement confirmation status', max_length=20),
        ),
    ]
